### ISSUE TITLE
 Capacitor community firebase crashlytics, app has stopped

### ISSUE THREAD

**Issue by mrkamlesh** [capacitor-community/firebase-crashlytics#13]
**Ionic with React**
 I tried to implement capacitor community firebase crashlytics and the bug is.

```
2020-09-06 13:38:55.946 13535-13535/? E/SchedPolicy: open of /dev/cpuctl/bg_non_interactive/tasks failed: No such file or directory
2020-09-06 13:38:56.583 13535-13535/com.xxx.xxx E/chromium: [ERROR:filesystem_posix.cc(62)] mkdir /data/user/0/com.xxx.xxx/cache/WebView/Crashpad: No such file or directory (2)
2020-09-06 13:38:59.365 13535-13535/com.xxx.xxx E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xxx.xxx, PID: 13535
    java.lang.InstantiationError: com.google.firebase.iid.zzbe
        at com.google.firebase.messaging.zzc.onBind(com.google.firebase:firebase-messaging@@20.1.2:11)
        at android.app.ActivityThread.handleBindService(ActivityThread.java:3457)
        at android.app.ActivityThread.-wrap2(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1729)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6626)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
 
```

**To Reproduce**
1. Followed the steps mentioned in README.md
2. Run into device using '$ ionic capacitor run android'
3. Open android studio and run app into device.
4. See error: '[App Name] has stopped'

**Screenshots**

![image](https://user-images.githubusercontent.com/8307491/92355014-0b981900-f101-11ea-988e-5c72ff71b822.png)

**Smartphone:**
 - Device tested on: [Android 8 and Android 10]

**Comment by robingenz** [comment]
I've updated all dependencies. This exception should now no longer occur. 
Please try the latest `dev` version: 
```
npm i @capacitor-community/firebase-crashlytics@0.3.0-dev.24949cd
```
Let me know if the problem persists.
