### ISSUE TITLE
App crashed first time launch and while receiving push notification every time once integrated this plugin into Capacitor Push notification enabled Ionic project

### ISSUE THREAD

**Issue by AndroidDaily** [capacitor-community/firebase-crashlytics#18]
Hi @priyankpat , @stewwan , @dwieeb , @thibaud-sanchez 

**Describe the bug**
App is crashing in below two scenarios:

1. On first time App launch
2. Whenever we receive push notification, when we use this plugin in capacitor based Ionic project which has Push Notification  
APIs integrated.

**To Reproduce**
1. Make Ionic + Angular capacitor project
2. Follow and integrate Capacitor core Push notification from https://capacitorjs.com/docs/guides/push-notifications-firebase
3. Integrate this crashlytics plugin in the same project
4. Send Push notification from firebase console

**Expected behavior**
App must not crash while receiving push notification.

**Smartphone (please complete the following information):**
 - Device: Android OnePlus 6
 - OS: Android 10

**Additional context**
Android Studio IDE - 4.1.1

** First time App launch crash log**

`			FATAL EXCEPTION: main
		Process: com.pg.you, PID: 28148
		java.lang.InstantiationError: com.google.firebase.iid.zzbe
			at com.google.firebase.messaging.zzc.onBind(com.google.firebase:firebase-messaging@@20.1.2:11)
			at android.app.ActivityThread.handleBindService(ActivityThread.java:4097)
			at android.app.ActivityThread.access$1900(ActivityThread.java:231)
			at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1973)
			at android.os.Handler.dispatchMessage(Handler.java:107)
			at android.os.Looper.loop(Looper.java:214)
			at android.app.ActivityThread.main(ActivityThread.java:7682)
			at java.lang.reflect.Method.invoke(Native Method)
			at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
			at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
`

**While receiving push notification, App crash logs**

` java.lang.NoSuchMethodError: No static method zza()Lcom/google/firebase/iid/zzaz; in class Lcom/google/firebase/iid/zzaz; or its super classes (declaration of 'com.google.firebase.iid.zzaz' appears in /data/app/com.pg.you-CXfkZKHd9QnYbA0XHEi7Fw==/base.apk)
        at com.google.firebase.messaging.FirebaseMessagingService.zza(com.google.firebase:firebase-messaging@@20.1.2:7)
        at com.google.firebase.messaging.zzc.onStartCommand(com.google.firebase:firebase-messaging@@20.1.2:22)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4204)
        at android.app.ActivityThread.access$2100(ActivityThread.java:231)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1984)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)`

**Comment by yigitbacakoglu** [comment]
same issue

**Comment by madiron** [comment]
I have the same problem

**Comment by adriaan** [comment]
This looks like the same issue as https://github.com/capacitor-community/firebase-analytics/issues/39 
Does updating to `firebaseMessagingVersion = '20.2.3'` in `variables.gradle` resolve the crash?

**Comment by madiron** [comment]
tnk adriaan, with this update it seems to work. 👍

**Comment by AndroidDaily** [comment]
After adding `implementation platform('com.google.firebase:firebase-bom:26.4.0')` in Android Module build.gradle file, 
problem get solved.

**Comment by praveen3637** [comment]
> `le` resolve the crash?

thanks it helped a lot
