### ISSUE TITLE
bug: Capacitor 2 Support?

### ISSUE THREAD

**Issue by SrinivasanTarget** [capacitor-community/firebase-crashlytics#36]
**Current behavior:**

I see the module uses 3.0-rc version of capacitor core. 

**Expected behavior:**

Is there any plans to support capacitor 2.x till the stable version of core is released?

**Steps to reproduce:**

My Sample app with the capacitor (core-2.x) doesn't build with 1.0 version of firebase crashlytics.

**Logs:**

```
Error: ./node_modules/@capacitor-community/firebase-crashlytics/dist/esm/index.js 2:28-42
"export 'registerPlugin' was not found in '@capacitor/core'
    at HarmonyImportSpecifierDependency._getErrors (/Users/sekars/workspace/firebase-example/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:109:11)
    at HarmonyImportSpecifierDependency.getErrors (/Users/sekars/workspace/firebase-example/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
    at Compilation.reportDependencyErrorsAndWarnings (/Users/sekars/workspace/firebase-example/node_modules/webpack/lib/Compilation.js:1463:22)
    at /Users/sekars/workspace/firebase-example/node_modules/webpack/lib/Compilation.js:1258:10
    at _next0 (eval at create (/Users/sekars/workspace/firebase-example/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
    at eval (eval at create (/Users/sekars/workspace/firebase-example/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:43:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Capacitor doctor:**

```
➜  firebase-example git:(master) ✗ npx cap doctor
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 2.4.7
  @capacitor/core: 2.4.7
  @capacitor/android: 2.4.7
  @capacitor/electron: 2.4.7
  @capacitor/ios: 2.4.7

Installed Dependencies:

  @capacitor/android not installed
  @capacitor/cli 2.4.7
  @capacitor/core 2.4.7
  @capacitor/ios 2.4.7
  @capacitor/electron not installed
```

**Comment by robingenz** [comment]
Capacitor 2 is supported up to `v0.4.0` (see [README.md](https://github.com/capacitor-community/firebase-crashlytics/tree/v0.4.0)).

```
npm install @capacitor-community/firebase-crashlytics@0.4.0
```
