### ISSUE TITLE
Error:The Crashlytics build ID is missing.

### ISSUE THREAD

**Issue by sattasundar** [capacitor-community/firebase-crashlytics#40]
After installing this latest(V1.0.0) in Capacitor 3 app. It getting crashed while running in emulator. Getting below error in logcat;

```
2021-06-16 14:24:25.215 1730-1730/com.wipro.mycommunication E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.wipro.mycommunication, PID: 1730
    java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.IllegalStateException: The Crashlytics build ID is missing. This occurs when Crashlytics tooling is absent from your app's build configuration. Please review Crashlytics onboarding instructions and ensure you have a valid Crashlytics account.
        at android.app.ActivityThread.installProvider(ActivityThread.java:6988)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6445)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalStateException: The Crashlytics build ID is missing. This occurs when Crashlytics tooling is absent from your app's build configuration. Please review Crashlytics onboarding instructions and ensure you have a valid Crashlytics account.
        at com.google.firebase.crashlytics.internal.common.CrashlyticsCore.onPreExecute(CrashlyticsCore.java:125)
        at com.google.firebase.crashlytics.FirebaseCrashlytics.init(FirebaseCrashlytics.java:142)
        at com.google.firebase.crashlytics.CrashlyticsRegistrar.buildCrashlytics(CrashlyticsRegistrar.java:58)
        at com.google.firebase.crashlytics.CrashlyticsRegistrar.lambda$Pfd5XmDCFzNyAT9o9H6rDnTBQE4(Unknown Source:0)
        at com.google.firebase.crashlytics.-$$Lambda$CrashlyticsRegistrar$Pfd5XmDCFzNyAT9o9H6rDnTBQE4.create(Unknown Source:2)
        at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0$ComponentRuntime(ComponentRuntime.java:132)
        at com.google.firebase.components.-$$Lambda$ComponentRuntime$4FqOW9eOQsvFYo-HpMfxCOnPQr0.get(Unknown Source:4)
        at com.google.firebase.components.Lazy.get(Lazy.java:53)
        at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:291)
        at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:281)
        at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:584)
        at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:303)
        at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:267)
        at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:252)
        at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:51)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2092)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2066)
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:45)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6983)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6445) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:219) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

Can anyone suggest what i am lacking for this?

**Comment by sattasundar** [comment]
```
2021-06-16 18:24:56.406 5337-5337/? I/FirebaseCrashlytics: Initializing Firebase Crashlytics 17.4.1
2021-06-16 18:24:56.494 5337-5337/? E/FirebaseCrashlytics: .
2021-06-16 18:24:56.494 5337-5337/? E/FirebaseCrashlytics: .     |  | 
2021-06-16 18:24:56.494 5337-5337/? E/FirebaseCrashlytics: .     |  |
2021-06-16 18:24:56.494 5337-5337/? E/FirebaseCrashlytics: .     |  |
2021-06-16 18:24:56.507 5337-5337/? E/FirebaseCrashlytics: .   \ |  | /
2021-06-16 18:24:56.508 5337-5337/? E/FirebaseCrashlytics: .    \    /
2021-06-16 18:24:56.508 5337-5337/? E/FirebaseCrashlytics: .     \  /
2021-06-16 18:24:56.508 5337-5337/? E/FirebaseCrashlytics: .      \/
2021-06-16 18:24:56.508 5337-5337/? E/FirebaseCrashlytics: .
2021-06-16 18:24:56.508 5337-5337/? E/FirebaseCrashlytics: The Crashlytics build ID is missing. This occurs when Crashlytics tooling is absent from your app's build configuration. Please review Crashlytics onboarding instructions and ensure you have a valid Crashlytics account.
2021-06-16 18:24:56.508 5337-5337/? E/FirebaseCrashlytics: .
2021-06-16 18:24:56.508 5337-5337/? E/FirebaseCrashlytics: .      /\
2021-06-16 18:24:56.508 5337-5337/? E/FirebaseCrashlytics: .     /  \
2021-06-16 18:24:56.508 5337-5337/? E/FirebaseCrashlytics: .    /    \
2021-06-16 18:24:56.508 5337-5337/? E/FirebaseCrashlytics: .   / |  | \
2021-06-16 18:24:56.508 5337-5337/? E/FirebaseCrashlytics: .     |  |
2021-06-16 18:24:56.508 5337-5337/? I/chatty: uid=10176(com.wipro.mycommunication) identical 1 line
2021-06-16 18:24:56.508 5337-5337/? E/FirebaseCrashlytics: .     |  |
2021-06-16 18:24:56.508 5337-5337/? E/FirebaseCrashlytics: .
2021-06-16 18:24:56.508 5337-5337/? D/AndroidRuntime: Shutting down VM
2021-06-16 18:24:56.524 2961-3615/com.google.android.gms I/Icing: Indexing com.google.android.gms-internal.3p:MobileApplication from com.google.android.gms using seqno 71
2021-06-16 18:24:56.526 5337-5337/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.wipro.mycommunication, PID: 5337
    java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.IllegalStateException: The Crashlytics build ID is missing. This occurs when Crashlytics tooling is absent from your app's build configuration. Please review Crashlytics onboarding instructions and ensure you have a valid Crashlytics account.
        at android.app.ActivityThread.installProvider(ActivityThread.java:6988)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6445)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalStateException: The Crashlytics build ID is missing. This occurs when Crashlytics tooling is absent from your app's build configuration. Please review Crashlytics onboarding instructions and ensure you have a valid Crashlytics account.
        at com.google.firebase.crashlytics.internal.common.CrashlyticsCore.onPreExecute(CrashlyticsCore.java:125)
        at com.google.firebase.crashlytics.FirebaseCrashlytics.init(FirebaseCrashlytics.java:207)
        at com.google.firebase.crashlytics.CrashlyticsRegistrar.buildCrashlytics(CrashlyticsRegistrar.java:54)
        at com.google.firebase.crashlytics.CrashlyticsRegistrar.access$lambda$0(Unknown Source:0)
        at com.google.firebase.crashlytics.CrashlyticsRegistrar$$Lambda$1.create(Unknown Source:2)
        at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0(ComponentRuntime.java:132)
        at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(Unknown Source:4)
        at com.google.firebase.components.Lazy.get(Lazy.java:53)
        at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:291)
        at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:281)
        at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:584)
        at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:303)
        at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:267)
        at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:252)
        at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:51)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2092)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2066)
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:45)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6983)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6445) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:219) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

**Comment by robingenz** [comment]
Thank you for your request.
Unfortunately, I could not reproduce the issue with my Android emulator (Pixel 3 XL API 30).
Please fill out the issue template correctly so that I have all the info I need.
Make sure you have followed the [installation](https://github.com/capacitor-community/firebase-crashlytics#installation) instructions correctly (especially the [Android part (Step 3)](https://firebase.google.com/docs/crashlytics/get-started?platform=android#add-sdk)).
